version: '3.8'

services:
  debttracker_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: debttracker_backend
    restart: always
    environment:
      PORT: 8080
      DB_HOST: 171.254.92.12
      DB_USER: root
      DB_PASSWORD: "${DB_PASSWORD:-123456}"
      DB_NAME: "${DB_NAME:-debt_tracker}"
    ports:
      - "8082:8080"
    networks:
      - debttracker_net

  debttracker_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: debttracker_frontend
    restart: always
    ports:
      - "8004:80"
    depends_on:
      - debttracker_backend
    networks:
      - debttracker_net

networks:
  debttracker_net:
    driver: bridge
